---
includeExts:
- ".yaml"
- ".sh"
- ".yml"
- ".md"
excludeLinks:
- "http://localhost"
- "https://localhost"
- "http://127.0.0.1"
- "https://127.0.0.1"
- "http://0.0.0.0"
- "https://0.0.0.0"
- "https://vault.example.com:8200"
- "$"
- "<"
- ">"
- "@"
excludeFiles:
- "cli/"
- ".git/"
- "docs/"
- ".gitignore"
- ".github/"
acceptStatusCodes:
- 200
- 201
- 302
- 401
- 403