---
includeExts:
- ".sh"
- ".md"
- ".yaml"
- ".yml"
excludeLinks:
- "http://localhost"
- "https://localhost"
- "http://127.0.0.1"
- "https://127.0.0.1"
- "http://0.0.0.0"
- "https://0.0.0.0"
- "https://vault.example.com:8200"
- "http://build-squid.eng.vmware.com/"
- "https://harbor-"
- "http://helloworld-go.default.18.204.46.247.xip.io"
- "https://example.com"
- "http://zipkin.istio-system.svc.cluster.local"
- "https://kubernetes.default.svc"
- "http://minio:9000"
- "$"
- "<"
- ">"
- "@"
excludePaths:
- ".git/"
- ".gitignore"
- ".github/"
acceptStatusCodes:
- 200
- 201
- 302
- 401
- 403
